name: WeaponsPlugin
main: me.jahaziel.weapons.WeaponsPlugin
version: 4.3-beta
api-version: 1.21
commands:
  ritual:
    description: Start a ritual to create a weapon (OP only)
  weapon:
    description: Reset crafted weapons (OP only)
  bounty:
    description: Place a bounty (crown wearer only)
permissions: {}
