name: WeaponsPlugin
version: '1.0-SNAPSHOT'
main: me.jahaziel.weapons.WeaponsPlugin
api-version: '1.21'
author: Jahaziel

commands:
  bounty:
    description: Place a bounty on a player
    usage: /bounty <player>
  ritual:
    description: Start a crafting ritual for an item
    usage: /ritual <scythe_of_light|scythe_of_darkness|wither_launcher|lifestealer|kings_crown>